# Site settings
title: Minh-Kha
description: Minh-Kha's Resume
# baseurl: "" # the subpath of your site, e.g. /blog
url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Hi, I'm Minh-Kha
user_description: I'm a final-year student of Industrial Engineering and Management at Karlsruhe Institute of Technology, always up for new challenges! Currently, I am immersed in my master thesis at ETH Zurich, where I try to identify future research fields through the application of NLP-techniques to research grant data.
user_title: Nice to meet you!
email: mknguyen1406@gmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
